### ISSUE TITLE
How to create Streaming Data Graph

### ISSUE THREAD

**Issue by erhansaydam** [alexcode/vue2vis#10]
Hi,
I would like to generate streaming data graph as in the official samples: http://visjs.org/examples/graph2d/15_streaming_data.html (Static selected)

How can I create such a graph with vue2vis graph2d component. In the official sample, it uses a renderStep function where it invokes a getWindow function to proceed. But vue2vis graph2d component does not involve a getWindow method.

Could you provide help to build a streaming data example?

Thank you.

Best regards,
Erhan Saydam

**Comment by alexcode** [comment]
I've never did a streaming graph this way but it should be doable.
And yes, we did forget to add `getWindow` and `setWindow`. If you feel like adding them it could be nice, otherwise I'll try to do that asap.

**Comment by erhansaydam** [comment]
Yes, make sure.

There are already setWindow method ready. I have added getWindow method to graph2d component and committed.

Best regards.

**Comment by alexcode** [comment]
@erhansaydam, do not hesitate to send a pull request ;)
