### ISSUE TITLE
Import problem with vue2vis.

### ISSUE THREAD

**Issue by Reollyn** [alexcode/vue2vis#16]
Hello,

when I try to import the timeline component as it says in the Readme I'm getting this error 

`'vue2vis' is not defined`.

I tried to import it like this `import Vue2Vis from 'vue2vis'` and then call it with `Vue2Vis.Timeline` but this does not works neither.

Does anyone know the solutiong for that. Thanks!

**Comment by Menighin** [comment]
Have you solved it? What was the problem?

**Comment by Reollyn** [comment]
Yes. 

I needed to import it like so `import { Timeline } from 'vue2vis'` and then I needed to declare that component `Vue.component('timeline', Timeline)`.
