### ISSUE TITLE
Events not working like drop and others.

### ISSUE THREAD

**Issue by Reollyn** [alexcode/vue2vis#17]
Hello,

I'm trying to make a drop event after I drag my items but when I drop it nothing happens the function that i set for the drop event is not called.

In my template I set the event for drop.

`<timeline v-if="items.length > 0" ref="timeline"
        :items="items"
        :groups="groups"
        :options="options"
        :events="['drop', 'changed']"
        @drop="myDropCallback()">
</timeline>`

And in `methods` I set the function.

`myDropCallback: function (value) {
      console.log('drop event')
  },`

Does anyone know why is this happening? Thanks.

**Comment by alexcode** [comment]
As @Mark-Hoog says, here is an exemple: https://jsfiddle.net/alexkodo/ejdut8fm/253/
