### ISSUE TITLE
Sorry, but I can`t run demo locally

### ISSUE THREAD

**Issue by veber1488** [alexcode/vue2vis#27]
I take all the steps, according to the manual: 

$ npm link
$ cd examples
$ npm install
$ npm link vue2vis
$ npm run dev
but I had an error. Am I doing smth wrong?
![error](https://user-images.githubusercontent.com/15994837/43756542-a60acab8-9a2e-11e8-9fc3-768a1af8ab0a.jpg)

**Comment by alexcode** [comment]
Did you run the command npm run build before linking?

Le mar. 7 août 2018 13:23, João Menighin <notifications@github.com> a
écrit :

**Comment by veber1488** [comment]
Yes, it's my fault. I did what you said and it made everything work for me. Thanks!
