### ISSUE TITLE
Trying to getTime on Graph2d

### ISSUE THREAD

**Issue by ricvillagrana** [alexcode/vue2vis#29]
Error when I am not actually using dates or time
`Error in mounted hook: "TypeError: Cannot read property 'getTime' of undefined"`

**Comment by alexcode** [comment]
Hi @ricvillagrana, could you add a JSFiddle which repro this bug.
Thanks.

**Comment by alexcode** [comment]
I would say this is related to visjs itself. Please reopen if you think otherwise.
