### ISSUE TITLE
 @stabilization-progress does not run sometimes

### ISSUE THREAD

**Issue by malaimoo** [alexcode/vue2vis#30]
I want to add a loding-bar when vis network is loading, so I add this 
```
network:
        @start-stabilizing="startStabilizing"
        @stabilization-iterations-done="stablelizingDone"
method:
     startStabilizing() {
        console.log('startStabilizing');
        this.topoloading = true;
      }, // to control loading status hidden or appear
     stablelizingDone(progress) {
        console.log('done');
        // this.topoloading = false;
      },
```
if I remove this method:`this.topoloading = true;` it will print both "startStabilizing" &  "done" .
If I add this `this.topoloading = true;` it will only print "startStabilizing" but no "done" ... It is wired.

**Comment by Menighin** [comment]
Hi, can you try reproducing it in a JSFiddle? I didn't understand what exactly is happening...

**Comment by malaimoo** [comment]
Hi, I creat a simple sample in JSFiddle , but It run well, and does not reproduce this bug that in my project, I think the bug is related with my project setting. Thank you.
