### ISSUE TITLE
Timeline lifecycle methods

### ISSUE THREAD

**Issue by erhansaydam** [alexcode/vue2vis#32]
Hi,
I could not use lifecycle methods of timeline . I tried to understand the document but could not understand. For example when timeline is mounted, I would like to focus an item ( i.e invoke focus method of timeline). I tried code below but could not succeed.
```
<template>
     <timeline ref="timeline_ref"
         :items="items"  :groups="groups"  :options="options"
@items-mounted="focusTimeline"> </timeline>
</template>

<script>
 //...
    methods:{
      focusTimeline(){
        this.$refs.timeline_ref.focus(3);
      }
    }
 //...
</script>
```
Best regards.

**Comment by alexcode** [comment]
I guess is because your $ref is not yet available (https://vuejs.org/v2/api/#ref)

**Comment by erhansaydam** [comment]
Hi @alexcode, Thank you for your reply, I have solved it by @items-update event.
