### ISSUE TITLE
Doubleclick on timeline is not working

### ISSUE THREAD

**Issue by erhansaydam** [alexcode/vue2vis#35]
Hi,
Doubleclick on timeline is not triggering the method.

`<timeline ref="refTimeline" :items="tlItems" :groups="groups" :options="options"
                      @doubleClick="addtoTimeline">`

the addtoTimeline method is not invoked when double clicked. It was working on previous releases.

Could you fix it.

Thank you,
Kind regards.

**Comment by chapuzzo** [comment]
Hi @erhansaydam, as you can see in this example the bound event must be `double-click` https://github.com/alexcode/vue2vis/blob/master/examples/src/App.vue#L67

I've been looking for it for a little...

**Comment by alexcode** [comment]
Yes, props are kebab-case in DOM templates https://vuejs.org/v2/guide/components-props.html#Prop-Casing-camelCase-vs-kebab-case

**Comment by erhansaydam** [comment]
Hi @alexcode, thank you very much, I have tested and no problem at all.
