### ISSUE TITLE
TypeError: Cannot read property 'redraw' of undefined

### ISSUE THREAD

**Issue by wildneuro** [alexcode/vue2vis#36]
When trying to do next:
```
this.$refs.network.redraw()
```
getting:
```
TypeError: Cannot read property 'redraw' of undefined
```

**Comment by alexcode** [comment]
Hi @wildneuro, this seems to be related to Vuejs instance lifecyle. The $refs are not available at the first render. 
https://github.com/alexcode/vue2vis/issues/32#issuecomment-444131561

**Comment by wildneuro** [comment]
Ok, will stick to another approach for now.
