### ISSUE TITLE
currentTimeTick event not firing for version > 0.0.13

### ISSUE THREAD

**Issue by JacopoKenzo** [alexcode/vue2vis#41]
Hi guys,

I have a simple Timeline component with few items.. 
one of them has to keep refreshing to maintain the end, right on the "currentTime" red line.

To do that I need the event currentTimeTick. 
Everything works perfectly with version 0.0.13 but if I update to the latest 0.0.16 it stop working.
Doesn't look like much changed across the versions.. am I doing something wrong?

My component:
```
            <timeline ref="timeline" class="timeline"
                      :groups="groups"
                      :items="items"
                      :options="options"
                      @items-mounted="getDataSet"
                      @currentTimeTick="currentTimeTick">
            </timeline>
```

Methods:
```
            getDataSet(dataSet) {
                this.dataSet = dataSet
            },
            currentTimeTick() {
                console.log("currentTimeTick");

                var lastItem = this.items[this.items.length - 1]
                
                if (lastItem != null) {
                     lastItem.end = moment().toDate();
                     this.dataSet.update(lastItem)
                }
            },
```

Edit: version 0.0.14 doesn't work. as soon as I switch back to 0.0.13 everything is fine.

**Comment by alexcode** [comment]
Maybe you can try to enable it with `:events="['currentTimeTick']"`.
