### ISSUE TITLE
Time line is not visible when items object is empty

### ISSUE THREAD

**Issue by zygisjas** [alexcode/vue2vis#46]
I have a weird issue, when I want to render a time line without any items, time line itself is invisible, i can see it in html code in dev-tools, but in browsers window It appears as invisible

**Comment by alexcode** [comment]
@zygisjas, any repro steps or JSFiddle ?

**Comment by NLegendre** [comment]
Hi @zygisjas

I had the same problem. A solution I found was to use some css :
```
.vis-timeline {
    visibility: visible !important;
}
```
To force the timeline to be visible all the time.

**Comment by alexcode** [comment]
@zygisjas, this is not related to this wrapper but to visjs itself. Please follow the solution provided by @NLegendre.
