### ISSUE TITLE
These relative modules were not found: ./img/...

### ISSUE THREAD

**Issue by tartinesKiller** [alexcode/vue2vis#5]
Hello,
When I try to use the library, at compile time, webpack throws these errors: 
```
ERROR  Failed to compile with 13 errors                                                                                                                                   

These relative modules were not found:

* ./img/network/addNodeIcon.png in ./node_modules/css-loader?{"sourceMap":false}!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-55649324","scoped":false,"hasI
nlineConfig":false}!./node_modules/stylus-loader?{"sourceMap":false}!./node_modules/vue-loader/lib/selector.js?type=styles&index=1!./src/components/xxx.vue
```

What could be wrong?

Thanks in advance, have a good day.

**Comment by Menighin** [comment]
Hi @tartinesKiller,
What were you trying to do? Just build? Can you tell me how you did it?

**Comment by tartinesKiller** [comment]
Hi, thanks for the answer, and sorry for not including sample
In my main.js:
```
import { Timeline } from "vue2vis";
...
Vue.component("timeline", Timeline);
...
```
And in my component:
```
<template>
    <div id="enclosingTimeline">
        <timeline :items="items" :options="options" :groups="groups" />
    </div>
</template>

<script>
import moment from "moment";
import Vue from "vue";

import "~vis/dist/vis.css";
...
```
~ is configured to be an alias for node_modules.
I think the css is imported as it should be, but it seems webpack couldn't find the vis.js images.
I've also found this discussion: [https://github.com/webpack-contrib/css-loader/issues/253](https://github.com/webpack-contrib/css-loader/issues/253) the errors seems similar, but the provided fix won't work.
If I manually copy the "img" folder from node_modules/vis to the place where my component is, it works, but I don't think it is a "long-term" fix.

Thanks again for your help, and thanks to all the contributors for this useful wrapper!

**Comment by Menighin** [comment]
Humm that's weird.

> If I manually copy the "img" folder from node_modules/vis to the place where my component is, it works.

This means you copy to where the vue2vis is or to where your component itself is?

Also, could you please try using Vis without Vue2Vis, importing the CSS, just to check if it would work?

**Comment by Menighin** [comment]
@tartinesKiller any news on this? 
I have cloned the project and used it without any problems... 
If it is working for you now could you please close the issue? 

Thanks!

**Comment by tartinesKiller** [comment]
Hello @Menighin, I'm sorry for the delay, but it's been a busy week, I'll try to spend some time to test it this evening. 
Thanks again, have a good day!

**Comment by Menighin** [comment]
Hi @erhansaydam, is it `vis.css` file?

If so, you should import it by yourself like we do in the examples [here](https://github.com/alexcode/vue2vis/blob/dd0fe00da6dff40f7513e512c43856d86eec2b29/examples/src/App.vue#L256)

@alexcode I think we should remove the `Vis` dependency from this project and let the user inject the version he wants too... Then this kind of problems vis-related should disappear... Been busy but will have a look on how to do it asap...

**Comment by alexcode** [comment]
@tartinesKiller, I believe the commit f0f6178 should solve this. Please let me know.

**Comment by tartinesKiller** [comment]
Hi, I'm sorry for the (very) long delay.

Unfortunately, even after the commit, the same error occurs.
However, the examples works well, so I guess the problem comes from my configuration of webpack.
I've tried one more time: doing @import "vue2vis/dist/vue2vis.css"; in style tag, webpack does not search images inside node_modules/vue2vis/etc, but in the folder where my components is located (creating a "images" folder and dropping all images inside the folder produces no errors). 
I am surely missing a key point in configuration, but can't figure out what.

Sorry to leave an issue opened so long, maybe we can close it? As it seems to be a problem with my configuration rather than with vue2vis.
Thanks again for the help!
