### ISSUE TITLE
Vis-4.21.0 EOL

### ISSUE THREAD

**Issue by satkunas** [alexcode/vue2vis#52]
The core `vis` package is EOL and no longer maintained.

https://www.npmjs.com/package/vis

Please consider using the following package instead so we can benefit from recent feature/enhancements:

https://github.com/visjs/vis-timeline

**Comment by suneab** [comment]
This update would be greatly appreciated. @alexcode

**Comment by alexcode** [comment]
@suneab I was working on other projects for a while but I'm planning to update this.

**Comment by suneab** [comment]
@alexcode thats fantastic news!
Do you have a rough estimate of when you're planning on releasing this?

**Comment by suneab** [comment]
@alexcode please reach out if you want help refactoring to the new version

**Comment by alexcode** [comment]
@suneab I would definitely use some help. I've just publish a new version within the [branch 1.x](https://github.com/alexcode/vue2vis/tree/1.x).
I've just ported the vis packages but there is still a lot to do (documentation, tests, build pipeline,...).
Feel free to submit PRs ;)
