### ISSUE TITLE
Infinite update loop with hierarchical

### ISSUE THREAD

**Issue by alucarddelta** [alexcode/vue2vis#53]
The console is reporting
> You may have an infinite update loop in watcher with expression "options"

When using the following code.

`<network
      class="network"
      ref="network"
      :nodes="this.vue2vis.nodes"
      :edges="this.vue2vis.edges"
      :options="options"`

`options: {
        layout: {
          hierarchical: {
            direction: "LR"
          }
        },
        nodes: {
          shape: "square"
        },
}`

When ever "hierarchical" is used even while empty, this message appears.

**Comment by setaman** [comment]
Have the same issue. I am injecting custom SVG and HTML to create nodes. So adding `{layout: {hierarchical: ...}}` breakes even custom nodes, nodes with default styles are displayed instead

**Comment by setaman** [comment]
you can walk around this issue by setting the `hierarchical` options manually like this:
```javascript
mounted() {
    this.$refs.network.setOptions({
      layout: {
        hierarchical: {
         ...
        }
      },
    });
  }
```

**Comment by alucarddelta** [comment]
That worked like a treat!

I ended up moving all my options into that def and it works perfectly!

Thanks @setaman
