### ISSUE TITLE
Dependency not found

### ISSUE THREAD

**Issue by bjschwarz** [alexcode/vue2vis#55]
Upon updating to 0.0.17 (the release from 2 days ago) I can no longer import the vue2vis library.

I get this: 

```
This dependency was not found:

vue2vis in ./src/main.js

To install it, you can run: npm install --save vue2vis

```

 I think the way to use the component changed to:

`Vue.component('timeline', vue2vis.Timeline);`

when before I was including the components like this:

`import { Timeline, DataSet } from 'vue2vis';`

@alexcode could you explain if the include process has changed with the updates?

**Comment by bjschwarz** [comment]
It appears that the /dist files are not being built properly. They don't exist at least with yarn. 

vue2vis.css - exists

vue2vis.js - not found
vue2vis.min.js - not found
vue2vis.min.js.map - not found

**Comment by alexcode** [comment]
@bjschwarz, this is due to the change in bundling tool used, the entry in the package.json must be changed. I'm fixing this but unfortunately I will need to publish a new version. Thanks for the report.
