### ISSUE TITLE
Wind feature is missing from physics option

### ISSUE THREAD

**Issue by szeref** [alexcode/vue2vis#59]
Hi Guys!

First of all thanks for your great work everything works fine! The only thing what I missing is the wind feature from physics option. This one:
[wind](https://visjs.github.io/vis-network/examples/network/physics/wind.html)

Is there a chance you will add that to the component?

**Comment by alexcode** [comment]
Hi @szeref, maybe you should check the alpha release `npm i @vue2vis/network@1.0.1-alpha.86` which will replace the current module.

**Comment by szeref** [comment]
> Hi @szeref, maybe you should check the alpha release `npm i @vue2vis/network@1.0.1-alpha.86` which will replace the current module.

Hi
