### ISSUE TITLE
Timeline: cluster options is not working

### ISSUE THREAD

**Issue by jungyitsai** [alexcode/vue2vis#68]
Hi, there

I found cluster options is not working in vue2vis. But vis is working.

- vue2vis demo ( not working )
  - https://codepen.io/jungyitsai/pen/RwRoLYj
  - console.log error
  ```
  Unknown option detected: "cluster" in options = {  cluster }
  ```

- vis demo ( working )
  - https://codepen.io/jungyitsai/pen/vYKyeOy

**Comment by alexcode** [comment]
I don't think the cluster option was available when I wrote the example. You might want to try with the latest version of the plugin.

**Comment by jungyitsai** [comment]
Yes, I see. sorry.
