### ISSUE TITLE
Not able to import the module.

### ISSUE THREAD

**Issue by nabeelalis** [alexcode/vue2vis#9]
I tried importing this.
`import { Timeline } from 'vue2vis';`
But it is giving me same error 
This dependency was not found:
```

* vue2vis in ./src/main.js

To install it, you can run: npm install --save vue2vis
> Listening at http://localhost:8080
```

**Comment by alexcode** [comment]
@nabeelalis did you tried to run `npm install --save vue2vis` ?

**Comment by nabeelalis** [comment]
Yes multiple times. But not working.

**Comment by Menighin** [comment]
Hi @nabeelalis,

Do you get an error when you run `npm install --save vue2vis`, right? Which error? The error you reported above seems to be because you are trying to use it without installing. So what is the error you get when you try to install it?

**Comment by nabeelalis** [comment]
Package.json file is updated. Also package is available in node _modules. I don't understand why it is getting the same error. I have tried installing it multiple times but still ran into this error while installing it.

**Comment by Menighin** [comment]
Hi @nabeelalis, investigating this I see there is some problem with the recently launched version `0.0.10`. Please update your `package.json` to use `0.0.9` and you should be good to go with the `Timeline` (0.0.9 doesnt have the `Network` component, though).

@alexcode, I don't know exactly how a package is made public on NPM, but it seems the build for it is not right. When I made the pull request with new configurations, I did altered the `npm run build` script on [this commit](https://github.com/alexcode/vue2vis/pull/3/commits/54b37330083d2c6ba3435133640520fc0ade146f), but, at least locally, it seems to be building just fine.
Can you help me investigate this?

**Comment by nabeelalis** [comment]
Sure I will look into this. I only need Timeline for now.

**Comment by alexcode** [comment]
@Menighin I should have checked better. I'll try to fix this ASAP.

**Comment by alexcode** [comment]
I've move the examples to a proper vue project in order to decorrelate the library from the examples dd0fe00da6dff40f7513e512c43856d86eec2b29.

The version 0.0.11 should be fixed https://jsfiddle.net/ejdut8fm/99/
